<?php defined('BASEPATH') or exit('No direct script access allowed');

trait ContentFormatAlert {
	public function formatCommonEmailSubject($subject = '', $data = []) {
		if (!empty($subject) && !empty($data)) {
			$find = [
				'{author_name}',
				'{owner_name}',
				'{username}',
				'{book_name}',
				'{url}',
				'{date}',
				'{first_name}',
				'{name}',
				'{school_name}',
				'{email}',
				'{mobile}',
				'{country}',
				'{state}',
				'{city}',
				'{designation}',
				'{grades}',
				'{sections}',
				'{authorized_person}',
				'{rank}',
				'{qrcode_file}',
				'{parent_name}',
				'{buyer_book_name}',
				'{buyer_book_author_name}',
				'{reviewer_book_name}',
				'{reviewer_book_author_name}',
			];

			$replace = [
				'author_name'				=> $data['author_name'] ?? '',
				'owner_name'				=> $data['owner_name'] ?? '',
				'username'					=> $data['username'] ?? '',
				'book_name'					=> $data['book_name'] ?? '',
				'url'						=> $data['url'] ?? '',
				'date'						=> !empty($data['datetime']) ? date('M j, Y', strtotime($data['datetime'])) : '',
				'first_name'				=> $data['first_name'] ?? '',
				'name'						=> $data['name'] ?? '',
				'school_name'				=> $data['school_name'] ?? '',
				'email'						=> $data['email'] ?? '',
				'mobile'					=> $data['mobile'] ?? '',
				'country'					=> $data['country'] ?? '',
				'state'						=> $data['state'] ?? '',
				'city'						=> $data['city'] ?? '',
				'designation'   			=> $data['designation'] ?? '',
				'grades'   					=> $data['grades'] ?? '',
				'sections'   				=> $data['sections'] ?? '',
				'authorized_person'   		=> $data['authorized_person'] ?? '',
				'rank'   					=> $data['rank'] ?? '',
				'qrcode_file'   			=> $data['qrcode_file'] ?? '',
				'parent_name'   			=> $data['parent_name'] ?? '',
				'buyer_book_name'   		=> $data['buyer_book_name'] ?? '',
				'buyer_book_author_name'   	=> $data['buyer_book_author_name'] ?? '',
				'reviewer_book_name'   		=> $data['reviewer_book_name'] ?? '',
				'reviewer_book_author_name' => $data['reviewer_book_author_name'] ?? '',
			];

			return str_replace($find, $replace, $subject);
		}
	}

	public function formatCommonEmailContent($content = '', $data = []) {
		if (!empty($content) && !empty($data)) {
			$find = [
				'{user_id}',
				'{site_id}',
				'{teacher_id}',
				'{author_name}',
				'{author_first_name}',
				'{owner_name}',
				'{username}',
				'{book_name}',
				'{url}',
				'{date}',
				'{date_2}',
				'{first_name}',
				'{name}',
				'{referrer_name}',
				'{school_name}',
				'{email}',
				'{mobile}',
				'{country}',
				'{state}',
				'{city}',
				'{designation}',
				'{grades}',
				'{sections}',
				'{authorized_person}',
				'{password}',
				'{student_url}',
				'{teacher_url}',
				'{qrcode_url}',
				'{school_dashboard_url}',
				'{teacher_dashboard_url}',
				'{rank}',
				'{qrcode_file}',
				'{student_url_link}',
				'{cert_url}',
				'{parent_name}',
				'{league_url}',
				'{buyer_book_name}',
				'{buyer_book_author_name}',
				'{reviewer_book_name}',
				'{reviewer_book_author_name}',
				'{url_link}',
				'{coupon}',
				'{coupon_percent}',
				'{duration}',
				'{label}',
				'{time}',
				'{count}',
			];

			$replace = [
				'user_id'					=> $data['user_id'] ?? 0,
				'site_id'					=> $data['site_id'] ?? 0,
				'teacher_id'				=> $data['teacher_id'] ?? 0,
				'author_name'				=> $data['author_name'] ?? '',
				'author_first_name'			=> $data['author_first_name'] ?? '',
				'owner_name'				=> $data['owner_name'] ?? '',
				'username'					=> $data['username'] ?? '',
				'book_name'					=> $data['book_name'] ?? '',
				'url'						=> $data['url'] ?? '',
				'date'						=> !empty($data['datetime']) ? date('M j, Y', strtotime($data['datetime'])) : '',
				'date_2'					=> !empty($data['duration_time']) ? date('M j, Y H:i:s', strtotime($data['duration_time'])) : '',
				'first_name'				=> $data['first_name'] ?? '',
				'name'						=> $data['name'] ?? '',
				'referrer_name'				=> $data['referrer_name'] ?? '',
				'school_name'				=> $data['school_name'] ?? '',
				'email'						=> $data['email'] ?? '',
				'mobile'					=> $data['mobile'] ?? '',
				'country'					=> $data['country'] ?? '',
				'state'						=> $data['state'] ?? '',
				'city'						=> $data['city'] ?? '',
				'designation'   			=> $data['designation'] ?? '',
				'grades'   					=> $data['grades'] ?? '',
				'sections'   				=> $data['sections'] ?? '',
				'authorized_person'   		=> $data['authorized_person'] ?? '',
				'password'   				=> $data['password'] ?? '',
				'student_url'   			=> $data['student_url'] ?? '',
				'teacher_url'   			=> $data['teacher_url'] ?? '',
				'qrcode_url'   				=> $data['qrcode_url'] ?? '',
				'school_dashboard_url'  	=> $data['school_dashboard_url'] ?? '',
				'teacher_dashboard_url' 	=> $data['teacher_dashboard_url'] ?? '',
				'rank' 						=> $data['rank'] ?? '',
				'qrcode_file'   			=> $data['qrcode_file'] ?? '',
				'student_url_link'   		=> $data['student_url_link'] ?? '',
				'cert_url'   				=> $data['cert_url'] ?? '',
				'parent_name'   			=> $data['parent_name'] ?? '',
				'league_url'   				=> $data['league_url'] ?? '',
				'buyer_book_name'   		=> $data['buyer_book_name'] ?? '',
				'buyer_book_author_name'   	=> $data['buyer_book_author_name'] ?? '',
				'reviewer_book_name'   		=> $data['reviewer_book_name'] ?? '',
				'reviewer_book_author_name' => $data['reviewer_book_author_name'] ?? '',
				'url_link' 					=> sprintf('<a href="%s" target="blank">%s</a>', ($data['url_link'] ?? ''), ($data['url_link'] ?? '')),
				'coupon' 					=> $data['coupon'] ?? '',
				'coupon_percent' 			=> $data['coupon_percent'] ?? 0,
				'duration' 					=> $data['duration'] ?? 0,
				'label' 					=> $data['label'] ?? '',
				'time'						=> !empty($data['time']) ? date('h:i A', strtotime($data['time'])) : '',
				'count' 					=> $data['count'] ?? '',
			];

			return str_replace($find, $replace, $content);
		}
	}
}
